#!/bin/bash
#export GPU_MAX_ALLOC_PERCENT=100
#export GPU_USE_SYNC_OBJECTS=1
#export GPU_SINGLE_ALLOC_PERCENT=100
#export GPU_MAX_HEAP_SIZE=100
#export GPU_FORCE_64BIT_PTR=1

#export GPU_FORCE_64BIT_PTR=0
#export GPU_MAX_HEAP_SIZE=100
#export GPU_USE_SYNC_OBJECTS=1
#export GPU_MAX_ALLOC_PERCENT=100
#export GPU_SINGLE_ALLOC_PERCENT=100

./ethdcrminer64 -tt -{FAN} -epool {ETHPOOL} -ewal {ETHWALLET}.{RIGID} -epsw {ETHPASS} -dpool {DCRPOOL} -dwal {DCRLOGIN}.{RIGID} -dpsw {DCRPASS} -dcri {DCRI}

